### ISSUE TITLE
Why standard instead of DataSet type control?

### ISSUE THREAD

**Issue by neronotte** [cathalnoonan/d365-pcf-securityrolemanager#1]
Hi Cathal,
very useful component, thank you very much for sharing. Just a question (not a real issue): is there a specific reason why you designed this component as a Standard type one instead of a DataSet type? It shows the list of roles bound to the current user, DataSet type feels more "natural"... is there a specific reason behind the choice?

Best regards,
Riccardo

**Comment by cathalnoonan** [comment]
Hi Riccardo,

Thanks for taking interest in the control

The control was designed before Security Roles had any support in the unified interface

(side note: Security Roles still don't seem to be fully implemented in the unified interface)
![image](https://user-images.githubusercontent.com/14317886/90177430-6f4d5180-dda2-11ea-95b7-3cf017111c17.png)

When the control was made, adding a grid of Security Roles to the form would display correctly on the classic interface, but not on the unified interface - this might have improved over the last few months, but I haven't tested it again

The aim of the control was to add missing features to the unified interface to give people a way to assign roles without needing to use the classic interface

Hope this helps to explain the reasons

Kind regards,
Cathal
