### ISSUE TITLE
Security Role Manager - Want to Filter the Security roles based on names

### ISSUE THREAD

**Issue by ishusharma0822** [cathalnoonan/d365-pcf-securityrolemanager#17]
### Description

I want to fetch only desired security roles based on the name, I have tried to compile source code but got multiple errors due to old NPM. I have also tried to update the web API url in the Bundle.js of managed solution [ roles?$select=name&$filter=name eq 'Analyst' or name eq 'Basic User' or  name eq 'System Administrator' ,roleid&$orderby=name asc ], but I am getting no records on the form. 
I would appreciate your Help.

### Steps to reproduce

.

### Version installed

2.0.2

**Comment by cathalnoonan** [comment]
Hi @ishusharma0822 

I would advise against modifying the `bundle.js` file inside the managed solution.
- There is no way to track that change in source control (e.g. git / tfs).
- If another member of your team has to make the same changes to the solution, they might not be aware of the manual changes when downloading the zip file from this repository.
- If there are new releases in this repository, you will have to make the changes manually again (which would be easy to miss if another member of your team is not aware of the changes and they were the one updating the control).

---

To clarify on your question, are you trying to filter the list of roles displayed **before** the user enters text in the search box?

i.e. before the screen below is shown?
![image](https://github.com/cathalnoonan/d365-pcf-securityrolemanager/assets/14317886/22eac3ff-e14b-4113-bd64-8860a27837ac)

**Comment by ishusharma0822** [comment]
Hi @cathalnoonan , Yes ,
 I just want to show 7-8 security roles instead of all the security roles.
 Is there any workaround?

**Comment by cathalnoonan** [comment]
Hi @ishusharma0822, this isn't implemented.

Some configuration is needed to get that working, it's something I may look into in the new year.

**Comment by cathalnoonan** [comment]
Hi @ishusharma0822, this is added in [v2.1.0](https://github.com/cathalnoonan/d365-pcf-securityrolemanager/releases/tag/v2.1.0).

**Comment by ishusharma0822** [comment]
Thank you for the Help!!
