### ISSUE TITLE
How to add a translation

### ISSUE THREAD

**Issue by Slowylowy** [cathalnoonan/d365-pcf-securityrolemanager#36]
### Description

Is there a way to add a translation for the component? Or just set the default to English always? 
For example; when the user language (and database language) is set to Dutch, the field label for business unit is displayed as "businessUnitId_Display_Key".

Thanks a lot!

**Comment by cathalnoonan** [comment]
Hi @Slowylowy, Dutch translations have been added in https://github.com/cathalnoonan/d365-pcf-securityrolemanager/releases/tag/v2.2.1
